### PR TITLE
[CMSSW 10_2] tag V01-01-03 + PRs #24 and #26

### PR DESCRIPTION
**Pull request by mrodozov**
See: 
https://github.com/cms-sw/cmssw/pull/29063#issuecomment-607813370

### CODE REVIEW

**Comment by slava77** [comment]
this PR still points to the master branch, will it actually be merged or will the target branch eventually be changed?

**Comment by slava77** [comment]
is there a cms-data maintenance limitation that restricts repos to just master branch?
A more straightforward way to support backports would require another upstream branch target available so that the backports are not polluting the history in the master branch

**Comment by mrodozov** [comment]
> is there a cms-data maintenance limitation

not sure, but I can check it making a new tag from 010103plus and use it in a 10_2 cmsdist PR.

**Comment by smuzaffar** [comment]
@slava77 , no there is no maintenance limit. 
@mrodozov , please create a branch (call it CMSSW_10_2_X) based on V01-01-03 and propose changes for that.

**Comment by mrodozov** [comment]
->  https://github.com/cms-data/RecoBTag-Combined/pull/29

**Pull request closed without merging**
