### PR TITLE
Add PartcileNet ONNX models for Run 3 PFScouting

### PR DESCRIPTION
**Pull request by alintulu**
This PR adds the necessary files for running 3 types of inference for Run 3 PFScouting. The 3 models include

- AK4 flavour-tagging
- AK8 b-tagging
- AK8 mass regression

You can find plots over the performance of each model [here](https://docs.google.com/presentation/d/1Z8j1_AmpV1C5U0ImYvcD6OgB7BpT08jATt0sREuYJbY/edit?usp=sharing).

We plan to redo the training for each model as soon as the improved Run 3 sample is ready (hopefully within a month). However as this PR is in combination with another to CMSSW adding a custom Run 3 PFScouting NanoAOD (https://github.com/cms-sw/cmssw/pull/40438), we would like to include these first versions of the models already now.

### CODE REVIEW

**Comment by alintulu** [comment]
Hi, what is the status on this PR? We are ready to move on with the CMSSW PR (https://github.com/cms-sw/cmssw/pull/40438), however it requires this PR to be merged first.

**Comment by smuzaffar** [comment]
@alintulu , these are all new files so should be OK to merge in to data repo. But lets first test with with the cmssw PR. I have started the tests for https://github.com/cms-sw/cmssw/pull/40438

**Comment by clacaputo** [comment]
+reconstruction

- tested in https://github.com/cms-sw/cmssw/pull/40438

**Comment by rappoccio** [comment]
+1

**Comment by mmusich** [comment]
as https://github.com/cms-sw/cmssw/pull/40438 was merged, shouldn't this one be merged as well?
The IB now complains about
```
----- Begin Fatal Exception 12-Oct-2023 07:01:19 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named step2_NANO.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file RecoBTag/Combined/data/Run3Scouting/ParticleNetAK4/V00/particle-net.onnx anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_13_3_X_2023-10-11-2300/poison:/data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_13_3_X_2023-10-11-2300/src:/data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_13_3_X_2023-10-11-2300/external/slc7_amd64_gcc11/data:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02806/slc7_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_X_2023-10-11-2300/poison:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02806/slc7_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_X_2023-10-11-2300/src:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02806/slc7_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_X_2023-10-11-2300/external/slc7_amd64_gcc11/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_13_3_X_2023-10-11-2300/pyRelval/2500.5_ScoutingNanodata13X
```
see [log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc11/CMSSW_13_3_X_2023-10-11-2300/pyRelValMatrixLogs/run/2500.5_ScoutingNanodata13X/step2_ScoutingNanodata13X.log#/).

Looks like `externals` signature is missing here @smuzaffar

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/8750 is merged and 11h IB should have the new data files

**Comment by alintulu** [comment]
Hi @smuzaffar! I tried  running a module that access a file part of this PR, but it returned the following error message

```
Exception Message:
edm::FileInPath unable to find file RecoBTag/Combined/data/Run3Scouting/ParticleNetAK4/V00/particle-net.onnx anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /tmp/adlintul/CMSSW_13_3_X_2023-10-11-2300/poison:/tmp/adlintul/CMSSW_13_3_X_2023-10-11-2300/src:/tmp/adlintul/CMSSW_13_3_X_2023-10-11-2300/external/slc7_amd64_gcc11/data:/cvmfs/cms-ib.cern.ch/sw/x86_64/week0/slc7_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_X_2023-10-11-2300/poison:/cvmfs/cms-ib.cern.ch/sw/x86_64/week0/slc7_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_X_2023-10-11-2300/src:/cvmfs/cms-ib.cern.ch/sw/x86_64/week0/slc7_amd64_gcc11/cms/cmssw-patch/CMSSW_13_3_X_2023-10-11-2300/external/slc7_amd64_gcc11/data
Current directory is: /tmp/adlintul/CMSSW_13_3_X_2023-10-11-2300/src/2500.5_ScoutingNanodata13X
```

I ran it in the IB release `CMSSW_13_3_X_2023-10-11-2300`. Do you know if I need to specify something for it to access the correct path or if I need to wait for a proper release before it is accessible? Thank you!

**Comment by smuzaffar** [comment]
@alintulu , you need to wait for today's 11h IB i.e. CMSSW_13_3_X_2023-10-12-1100 (hopefully it will be available in 4 hours)

**Comment by alintulu** [comment]
> @alintulu , you need to wait for today's 11h IB i.e. CMSSW_13_3_X_2023-10-12-1100 (hopefully it will be available in 4 hours)

Aaah sorry! I didn't make the connection with 11h, thank you!

**Pull request merged**
