### PR TITLE
Technical update to the DeepJet and DeepDoubleX TF models

### PR DESCRIPTION
**Pull request by hqucms**
A few technical updates to the TF models (e.g., remove nodes that are only used for training like `cpf_input_batchnorm/keras_learning_phase` from the graph, fix the DeepDoubleX models for batch inference). No change in the output is expected. Small (5-10%) speedup and slightly reduced model size.

The models are converted from the original Keras models using
https://github.com/hqucms/keras_to_tensorflow/blob/master/keras_to_tensorflow.py

**[Updated on backward compatibility]**

These models are intended to be used together w/ https://github.com/cms-sw/cmssw/pull/29172, though it is OK to merge this PR (the DNN models) before https://github.com/cms-sw/cmssw/pull/29172, because currently the inference in CMSSW is using ONNX (since https://github.com/cms-sw/cmssw/pull/28112), so these TF models are not really used. 

These models are NOT compatible w/ older releases (before https://github.com/cms-sw/cmssw/pull/28112) -- one needs to remove the `learning_phase` input in https://github.com/cms-sw/cmssw/blob/8a7ee7592d72cc40cc0a95c371787ccc49f520b1/RecoBTag/TensorFlow/plugins/DeepDoubleXTFJetTagsProducer.cc#L136 and https://github.com/cms-sw/cmssw/blob/8a7ee7592d72cc40cc0a95c371787ccc49f520b1/RecoBTag/TensorFlow/plugins/DeepFlavourTFJetTagsProducer.cc#L141 to use these new models.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by emilbols** [comment]
Sorry for the stupid question, but I realize im not entirely sure how a CMSSW release interfaces with this data directory. If this gets merged, what releases of CMSSW will pick up the models from the master of this branch? Only releases going forward? And will all those releases actually have the ONNX implementation? For instance i believe onnx was added in CMSSW_11_1_0_pre1, but it is not in CMSSW_11_0_1 which from the release notes, looks to be released after CMSSW_11_1_0_pre1.

**Comment by slava77** [comment]
@emilbols 
all release branches are independent, apart from the future new master with a new release number inheriting everything at a single point in time from the previous one.
You need (to look for) a PR in each corresponding numbered branch. Code or data files do not magically appear in locations needed by someone.

**Comment by hqucms** [comment]
> Sorry for the stupid question, but I realize im not entirely sure how a CMSSW release interfaces with this data directory. If this gets merged, what releases of CMSSW will pick up the models from the master of this branch? Only releases going forward? And will all those releases actually have the ONNX implementation? For instance i believe onnx was added in CMSSW_11_1_0_pre1, but it is not in CMSSW_11_0_1 which from the release notes, looks to be released after CMSSW_11_1_0_pre1.

@emilbols From my knowledge, the data repo is versioned on github, and which version to use is managed in https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_1_X/master/data/cmsswdata.txt.
For a specific release, you can find the version of the data directory in e.g., `$CMSSW_BASE/config/toolbox/slc7_amd64_gcc700/tools/selected/cmsswdata.xml`.

**Comment by smuzaffar** [comment]
@hqucms , should we close this PR ( https://github.com/cms-sw/cmssw/pull/29172 was closed too).

**Comment by hqucms** [comment]
@smuzaffar Yes this is no longer needed -- let me close it.

**Pull request closed without merging**
