### PR TITLE
[10_6_X] Add AK8 ParticleNet mass regression model

### PR DESCRIPTION
**Pull request by hqucms**
Backport of https://github.com/cms-data/RecoBTag-Combined/pull/44 for 10_6_X.

### CODE REVIEW

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/33588#issuecomment-832053040

**Comment by jpata** [comment]
This test does not look correct, it ran using 12_0_X. This PR was already tested in https://github.com/cms-sw/cmssw/pull/33588#issuecomment-832053040.

**Comment by mrodozov** [comment]
please test for CMSSW_10_6_X

**Comment by mrodozov** [comment]
+externals

**Comment by mrodozov** [comment]
right. the test is fine

**Pull request merged**
