### PR TITLE
Introduce DeepFlavour training jsons

### PR DESCRIPTION
**Pull request by mverzett**
This update should be distributed in 90X, 80X, and 81X cycles.

### CODE REVIEW

**Comment by slava77** [comment]
@smuzaffar, @iahmad-khan,
please note that this just adds a new file.
So, tests should be rather trivial if necessary at all and integration can be quick.

**Comment by mverzett** [comment]
@smuzaffar, @iahmad-khan,
It looks like that the files were propagated to 90X, but not 80X. Could you propagate it asap? The backporting PR fails due to the missing training files. Can you also let me know when they will become available?

Thanks

**Comment by smuzaffar** [comment]
I am doing it now

**Comment by smuzaffar** [comment]
done here https://github.com/cms-sw/cmsdist/pull/2845

**Comment by mverzett** [comment]
@smuzaffar Do I understand it correctly that it will appear in the next IB?

**Comment by smuzaffar** [comment]
yes it will.

**Pull request merged**
