### PR TITLE
add DeepFlavourV01 in CMSSW-DNN C-based format

### PR DESCRIPTION
**Pull request by pablodecm**
This PR adds the same model than https://github.com/cms-data/RecoBTag-Combined/pull/7 but in a new format which is compatible with the latest CMSSW C-based interface of Tensorflow developed by @riga and which will be used in https://github.com/cms-sw/cmssw/pull/19893.

The files contained in this PR contain the latest model for the DeepFlavour tagger, trained for jets up to eta=2.5, based on the CMS Phase 1 detector design, and on simulation of 80 million jets from ttbar and QCD events.

### CODE REVIEW

**Comment by slava77** [comment]
@pablodecm please remove the other format version after this is merged and the code in CMSSW PR is updated.

**Comment by pablodecm** [comment]
@slava77 I will do another PR with the old format removal then

**Comment by mrodozov** [comment]
Follow the tests here https://github.com/cms-sw/cmsdist/pull/3336

**Comment by smuzaffar** [comment]
this should be part of next 93X IB (2017-08-07-2330)

**Pull request merged**
