### PR TITLE
added chargeTag weights (16Jan)

### PR DESCRIPTION
**Pull request by aboletti**
added weights for the charge tagger in the RecoBTag/Combined package

### CODE REVIEW

**Comment by slava77** [comment]
@smuzaffar @degano 
we need this PR +  cms-sw/cmsdist#2058 integrated for https://github.com/cms-sw/cmssw/pull/12952

**Comment by ghost** [comment]
@slava77 sure, I'll merge it now and make the corresponding CMSDIST update.

**Comment by slava77** [comment]
On 1/19/16 6:00 AM, Alessandro Degano wrote:

> @slava77 https://github.com/slava77 sure, I'll merge it now and make
> the corresponding CMSDIST update.

Thank you!

**Comment by ghost** [comment]
Done in cms-sw/cmsdist#2062. Will go in the next IB (CMSSW_8_0_X_19-01-2016-2300)

**Pull request merged**
