### PR TITLE
adding onnx models for DeepVertex and DeeJet+DeepVertex combination

### PR DESCRIPTION
**Pull request by leonardogiannini**
As in the title: I'm adding onnx models for DeepJet and DeepVertex and removing the .pb models for these taggers

A PR to cmssw will integrate this update

@emilbols

### CODE REVIEW

**Comment by mrodozov** [comment]
Hi, do you have any cmssw PR to test this with ? 
I see one file (entirely?) removed. If you do let me know I'll start the test with it

**Comment by leonardogiannini** [comment]
this is the PR https://github.com/cms-sw/cmssw/pull/31988

Since the new taggers are not in the default workflow, you need to edit manually the expanded cfg to test.

removing the pb file is ok (it's outdated and similarly not in the default workflow)
 
Even RecoBTag/TensorFlow is all outdated at this point @emilbols ?

**Comment by emilbols** [comment]
@leonardogiannini In principle we did keep the TF models in this repository for the other taggers, but i am fine with removing the TF version for DeepVertex, after all we are just updating the model format here.

**Comment by emilbols** [comment]
@mrodozov @jpata @slava77 Can we have this one merged? We need it to run the corresponding merged CMSSW PR https://github.com/cms-sw/cmssw/pull/31988 .

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
if something in cmssw was using this (unless not conditionally) I don't see how  cms-sw/cmssw#31988 didn't fail.

**Comment by leonardogiannini** [comment]
> if something in cmssw was using this (unless not conditionally) I don't see how [cms-sw/cmssw#31988](https://github.com/cms-sw/cmssw/pull/31988) didn't fail.

The file removed was called by modules updated by the PR, which now use the updated files. It was also called conditionally, so unless one wants to use exactly the release with the older version and switch on the specific module there is no failure.

**Comment by mrodozov** [comment]
got it. if the test passes im merging it

**Pull request merged**
