### PR TITLE
backport of DeepVertex models

### PR DESCRIPTION
**Pull request by leonardogiannini**
applying to 10_6_x the same changes as in the master for the Deepvertex and combination models (see PR https://github.com/cms-data/RecoBTag-Combined/pull/37)

### CODE REVIEW

**Comment by mrodozov** [comment]
same as #37 ? I mean no need for cmssw pr ?

**Comment by mrodozov** [comment]
please test

**Comment by jpata** [comment]
The corresponding CMSSW PR (backport) is here: https://github.com/cms-sw/cmssw/pull/32647

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#32647

**Comment by silviodonato** [comment]
merge

**Pull request merged**
