### PR TITLE
Update DeepBoostedJet json to match the MXNet version.

### PR DESCRIPTION
**Pull request by hqucms**
This is intended to get rid of the printouts mentioned in https://github.com/cms-sw/cmssw/pull/23768#issuecomment-405913208. The content of the model is not changed.

### CODE REVIEW

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
I think that this change is simple enough that it can be merged and a cmsdist PR can be made so that we can check this in jenkins in connection with the cms-sw/cmssw#23768

**Comment by smuzaffar** [comment]
@slava77 , cmsdist PR is https://github.com/cms-sw/cmsdist/pull/4317

**Comment by smuzaffar** [comment]
@hqucms , we are now using mxnet 1.5.0 in CMSSW_11_0_X. Can you please update these json files for the new version to avoid the warnings [a]? 

[a]
https://github.com/cms-sw/cmsdist/pull/5146#issuecomment-525181924
```
26-Aug-2019 13:01:22 CEST Successfully opened file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_6_0/RelValMinBias_13/GEN-SIM/106X_mc2017_realistic_v3-v1/10000/5F6D4D28-A5D2-6A48-B327-5C827D7F53FB.root
[13:01:28] .../mxnet-predict/1.5.0/mxnet-predict-1.5.0/src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.1. Attempting to upgrade...
[13:01:28] .../mxnet-predict/1.5.0/mxnet-predict-1.5.0/src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[13:01:29] .../mxnet-predict/1.5.0/mxnet-predict-1.5.0/src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.1. Attempting to upgrade...
[13:01:29] .../mxnet-predict/1.5.0/mxnet-predict-1.5.0/src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
```

FYI @davidlange6

**Comment by hqucms** [comment]
> @hqucms , we are now using mxnet 1.5.0 in CMSSW_11_0_X. Can you please update these json files for the new version to avoid the warnings [a]?
> 
> [a]
> [cms-sw/cmsdist#5146 (comment)](https://github.com/cms-sw/cmsdist/pull/5146#issuecomment-525181924)
> 
> ```
> 26-Aug-2019 13:01:22 CEST Successfully opened file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_6_0/RelValMinBias_13/GEN-SIM/106X_mc2017_realistic_v3-v1/10000/5F6D4D28-A5D2-6A48-B327-5C827D7F53FB.root
> [13:01:28] .../mxnet-predict/1.5.0/mxnet-predict-1.5.0/src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.1. Attempting to upgrade...
> [13:01:28] .../mxnet-predict/1.5.0/mxnet-predict-1.5.0/src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
> [13:01:29] .../mxnet-predict/1.5.0/mxnet-predict-1.5.0/src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.1. Attempting to upgrade...
> [13:01:29] .../mxnet-predict/1.5.0/mxnet-predict-1.5.0/src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
> ```
> 
> FYI @davidlange6

@smuzaffar 
Should be fixed by https://github.com/cms-data/RecoBTag-Combined/pull/24

**Pull request merged**
