### PR TITLE
added July13 cMVAv2 weights

### PR DESCRIPTION
**Pull request by jpata**
First addition of cMVAv2 compressed training weights.

For https://github.com/cms-sw/cmssw/pull/10197.

### CODE REVIEW

**Comment by ghost** [comment]
@davidlange6

**Comment by davidlange6** [comment]
@degano +1 from me - likely needed for 74x,75x,76x

**Comment by slava77** [comment]
@degano, please merge this

**Comment by ghost** [comment]
@slava77 @jpata I've included it in 76X here: https://github.com/cms-sw/cmsdist/pull/1727.
Will do for 7[4-5]X once you'll verify in 76X that everything's good.

**Pull request merged**
