### PR TITLE
Adding SONIC structure for new ParticleNet and Higgs IN models + ONNX model update

### PR DESCRIPTION
**Pull request by wpmccormack**
Companion PR to https://github.com/cms-sw/cmssw/pull/43138.  Adding required model structure and configuration files for SONIC implementation of ParticleNet (PN) from MiniAOD for Ak4 and Ak8 jets.  Also including the Higgs Interaction network, as that is run through the same producer as PN.  Structure of additions and use of symbolic links for model files was previous approved and used here: https://github.com/cms-data/RecoBTag-Combined/pull/48.

Tagging @kpedro88 @yongbinfeng @violatingcp

### CODE REVIEW

**Comment by kpedro88** [comment]
@wpmccormack to fix the runTheMatrix failures in https://github.com/cms-sw/cmssw/pull/43138, you need to use the exact approach from https://github.com/cms-data/RecoBTag-Combined/pull/48: rather than making the *file* `x.onnx` a symlink, make a symlinked *directory* `modelfile` that points to `../../models/x/1` and then replace `x.onnx` with `modelfile/model.onnx` in the relevant CMSSW configs.

**Comment by wpmccormack** [comment]
Ahh yes, sorry I've fixed that now

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
