### PR TITLE
Merge HLT DeepJet models for Run3

### PR DESCRIPTION
**Pull request by NiclasEich**
The BTV@HLT group has developed a dedicated recalibration of the DeepJet tagger for the new trigger paths, mentioned during the [trigger reviews](https://indico.cern.ch/event/1099590/contributions/4626735/attachments/2358514/4025643/03_12_21_BTV_triggerreview.pdf).
After testing by several analysts, the model has found to be ready for deployment (see [BTV-WG meeting](https://indico.cern.ch/event/1112381/contributions/4676573/attachments/2376286/4059284/220120_BTV%40HLT%E2%80%93news.pdf)).

We deployed everything in a dedicated HLT subdirectory for better organization towards the future when more models might be deployed at HLT-level.

@SWuchterl

### CODE REVIEW

**Comment by NiclasEich** [comment]
Could anybody give an update on who is responsible for this? Many people got pinged automatically.

**Comment by smuzaffar** [comment]
@NiclasEich , is there any cmssw PR to test this newly added file?

**Comment by jpata** [comment]
sorry, this escaped reco attention. can we test it here with the bot, i.e. is a code change required at all, or is it just a drop-in model file replacement?

**Comment by smuzaffar** [comment]
@jpata , yes you can start the test here by commenting `please test`, but as this PR just adds a new file so I doubt any test will use it.

**Comment by jpata** [comment]
That's true, looks like the model file `DeepFlavour_220104.onnx` is not used anywhere in CMSSW. So a corresponding code change to use the model would be required @NiclasEich.

**Comment by emilbols** [comment]
@jpata This is a model that will only be used in HLT. In the confdb the trigger path is configured to use this model, so we dont actually need a module that uses it in CMSSW. I guess specifically the setting in confDB would be changing [1]  to the model name, but @NiclasEich would have to confirm. I dont know what procedure for adding HLT models in these repos was in the past, but it would be nice to have all models centralized.

[1]
https://github.com/cms-sw/cmssw/blob/master/RecoBTag/ONNXRuntime/plugins/DeepFlavourONNXJetTagsProducer.cc#L82-L83

**Comment by jpata** [comment]
unassign reconstruction

**Comment by jpata** [comment]
assign hlt

**Comment by missirol** [comment]
Thanks, @jpata (I see that "unassign reconstruction" didn't work, but I get the point).

> In the confdb the trigger path is configured to use this model

I guess this statement refers to users configs used by BTV in ConfDB. Obviously, the HLT menus maintained by TSG and included in CMSSW don't use this new model yet. This HLT change has to be requested on JIRA, and then the updated menu would be PR'd to CMSSW, and by then this new model would need to be available (actually, a bit earlier for testing purposes).

@NiclasEich @SWuchterl what is the timeline for the corresponding JIRA ticket?

**Comment by SWuchterl** [comment]
@missirol 
We can open the corresponding JIRA ticket as soon as possible. Our understanding was that first, we need to get the model file included. But if we need a dedicated PR for testing, we could open the JIRA first.
We'll do as suggested.

**Comment by missirol** [comment]
I would suggest to open the JIRA, and have this PR merged before the next pre-release (`12_3_0_pre5`) if others agree. Once the new pre-release is available, the HLT menu for `12_3_0_pre5` can be updated to use the new model.

**Comment by NiclasEich** [comment]
Thanks for the clarifications, we have opened a corresponding [JIRA-ticket](https://its.cern.ch/jira/browse/CMSHLT-2222) @missirol .

**Comment by missirol** [comment]
+hlt

I tested manually an updated HLT menu using this new input, based on the information in [CMSHLT-2222](https://its.cern.ch/jira/browse/CMSHLT-2222).

Based on https://github.com/cms-data/RecoBTag-Combined/pull/46#issuecomment-1025939265 , I'm not sure if running the usual PR tests here is of any use.

Edit: the signature triggered the tests (didn't know that).

**Comment by missirol** [comment]
The PR tests failed; this is almost certainly unrelated to this PR, but I don't understand what caused the problem.

The compilation errors point to cms-sw/cmssw#36773, which was merged earlier today, but was not included in `CMSSW_12_3_X_2022-02-01-1100` (and I could not find this type of PR-test failure elsewhere).

**Comment by smuzaffar** [comment]
please test

**Comment by missirol** [comment]
> For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-data/RecoBTag-Combined/46/22130/install.sh` to create a dev area with all the needed externals and cmssw changes.

Going back to the failed tests, I'm missing something about the area returned by the command above.

The area in question is checked out at commit `3e98b1bf159` , which seems to be what `master` was when the failed tests were started; `3e98b1bf159` includes a few PRs on top of `CMSSW_12_3_X_2022-02-01-1100` (among them, cms-sw/cmssw#36773).

The area has packages checked out locally; these look like the packages returned by `git cms-checkdeps -A -a` (plus, a few more). On the other hand, I was expecting to see also the packages modified between `CMSSW_12_3_X_2022-02-01-1100` and `3e98b1bf159` , and I don't see all of those.

The following reproduces the compile-time error from the bot
```bash
cmsrel CMSSW_12_3_X_2022-02-01-1100
cd CMSSW_12_3_X_2022-02-01-1100/src
cmsenv
git cms-init
git checkout -b tmp 3e98b1bf159
git cms-checkdeps -A -a
scram b
```

I'd be grateful if an expert could clarify.

**Comment by smuzaffar** [comment]
@missirol , although bot was using the master branch but it did not actually checkout the change between CMSSW_12_3_X_2022-02-01-1100 and master. The change https://github.com/cms-sw/cms-bot/pull/1704/files should fix this

**Comment by missirol** [comment]
Thanks, @smuzaffar !

**Comment by jpata** [comment]
+reconstruction
- the reco sig here is not required, but since the bot didn't remove the label, I'm signing it as is (no checking was done on my side)

**Comment by missirol** [comment]
@smuzaffar @perrotta @qliphy 

This PR contains new data files that TSG (cc: @silviodonato) would like to have in `12_3_0_pre5`; these files are needed by HLT developers of the BTV POG for upcoming updates to the HLT menu (documented in [CMSHLT-2222](https://its.cern.ch/jira/browse/CMSHLT-2222)).

If you see any problems with approving this PR, please let us know.

**Comment by smuzaffar** [comment]
+externals
it just adds a new file so I am fine with it.

**Comment by missirol** [comment]
@perrotta @qliphy

Just a kind reminder of this cms-data PR. It adds a new file that will be needed by HLT. It does not affect any existing wf.

**Comment by qliphy** [comment]
+1

**Pull request merged**
