### PR TITLE
Add UParTAK4 model

### PR DESCRIPTION
**Pull request by AlexDeMoor**
This PR add the onnx file of the new Unified Particle Transformer models for its cmssw integration. This network will perform an inclusive tagging combining b/c/tau/lep jet identification and jet energy regression (both the regression and the resolution estimation via quantile regression). The model is trained with a specific robust training combining adversarial training and domain adaptation for reducing the impact of the data/MC disagreement on the final performance. The output nodes of the domains are also kept for exploring the possibility of efficiency mapping and their impact later.

Please note: a last training is ongoing trying to improve the current performance via an enriched dataset. A modification of the final model could occur. Please don't merge this PR before Tuesday.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
+1

**Comment by hqucms** [comment]
The new model in commit https://github.com/cms-data/RecoBTag-Combined/pull/57/commits/7201375610ac3dbfc05720cbf9ad8978a9418a43 is re-tested at https://github.com/cms-sw/cmssw/pull/44641#issuecomment-2059491391.

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
