### PR TITLE
DNN models for the ParticleNet tagger

### PR DESCRIPTION
**Pull request by hqucms**
This PR adds the MXNet models of the ParticleNet tagger.

### CODE REVIEW

**Review by slava77 — COMMENTED** [review]
In DeepBoostedJet we have version first, and then full and decorrelated subdirs.
Please adjust the structure, especially if "MD" and non-MD are expected to appear simultaneously

It may be a good time to start populating README.md in the main directory and perhaps also in the subdirs to keep track of the files details.

**Comment by hqucms** [comment]
@slava77 
> In DeepBoostedJet we have version first, and then full and decorrelated subdirs.
> Please adjust the structure, especially if "MD" and non-MD are expected to appear simultaneously

I would prefer to keep the current structure as in the ParticleNet case, the two versions are not as closely coupled as in the case for DeepAK8 -- The nominal (non-MD) ParticleNet targets Top/W/Z/H tagging, similar to DeepAK8, while ParticleNet-MD is for mass-independent 2-prong tagging (X->bb, X->cc, X->qq) -- This means that we actually might want to update one but not the other. 
 
> It may be a good time to start populating README.md in the main directory and perhaps also in the subdirs to keep track of the files details.

Good idea! I will add a readme for them.

**Comment by slava77** [comment]
> I would prefer to keep the current structure as in the ParticleNet case, the two versions are not as closely coupled as in the case for DeepAK8


is ParticleNet name uniquely identifying the potential uses?
Should we at least add AK8 to the name of the files or dirs?
Perhaps ParticleNet/MD and ParticleNet/General (or alike) is still better; so that the training files are compartmentalized a bit better.

**Comment by hqucms** [comment]
@slava77 
How about `ParticleNetAK8/General/V00` and `ParticleNetAK8/MD-2prong/V00`?

**Comment by slava77** [comment]
> How about `ParticleNetAK8/General/V00` and `ParticleNetAK8/MD-2prong/V00`?

sounds good to me.

**Comment by hqucms** [comment]
@slava77 Done in https://github.com/cms-data/RecoBTag-Combined/pull/26/commits/aca78b92f3aaa6cb920e228aa74d7edf774518cc.

**Comment by silviodonato** [comment]
@perrotta @slava77 Do you have further comments?
 @mrodozov @smuzaffar @tulamor

**Comment by silviodonato** [comment]
@perrotta @slava77 Do you have other comments on this PR and https://github.com/cms-sw/cmssw/pull/28902 ?
@mrodozov @smuzaffar @tulamor

**Comment by smuzaffar** [comment]
+externals
> DQMHistoTests: Total failures: 40

@slava77 , any idea about these comparison failures?

**Comment by slava77** [comment]
> +externals
> 
> > DQMHistoTests: Total failures: 40
> 
> @slava77 , any idea about these comparison failures?

the DQM diffs are apparently related to #29076.
Changes in reco are expected due to cms-sw/cmssw#28902 (a part of the test results)

**Comment by slava77** [comment]
+1

this appears to be ready to go based on what was seen so far in cms-sw/cmssw#28902

**Comment by silviodonato** [comment]
+1

**Pull request merged**
