### PR TITLE
DDXV2

### PR DESCRIPTION
**Pull request by andrzejnovak**
Model files for https://github.com/cms-sw/cmssw/pull/30016

| BvL  | CvL | CvB |
| ------------- | ------------- | ------------- |
| ROCComparison_DDBvL2017pt300-1200 | ROCComparison_DDCvL2017pt300-1200| ROCComparison_DDCvB2017pt300-1200 |

### CODE REVIEW

**Comment by silviodonato** [comment]
merge

**Comment by smuzaffar** [comment]
@mrodozov , looks like this did not create the tag and PR for cmsdist.

**Comment by smuzaffar** [comment]
can you please check why jenkins job did not run and created the tag.
For now please create the tag by hand and open cmsdist PR, merge it so that 11h00 IB can work

**Comment by mrodozov** [comment]
because there was a release tagged by hand and the release name was V01-01-03-01 , I've updated it

**Comment by smuzaffar** [comment]
can youplease fix the tagging script to deal with these tags?

**Comment by mrodozov** [comment]
sure, only how to deal with the forth part (if found) ? 
I can assume the tag was done as tmp tag by hand, discard the forth part and update the other parts as usual ?

**Comment by smuzaffar** [comment]
we should only look for VNN-NN-NN tags and ignore any others.

**Comment by silviodonato** [comment]
@mrodozov same thing for https://github.com/cms-data/RecoBTag-Combined/pull/30

**Comment by mrodozov** [comment]
well yes but now the last tag should include both 30 and 31
ah if you mean that it failed also for 30, yes, because the tag was the same.

**Comment by silviodonato** [comment]
right, thanks. @smuzaffar could you restart the IB including https://github.com/cms-sw/cmsdist/pull/6049 and https://github.com/cms-sw/cmsdist/pull/6048? . They are needed for https://github.com/cms-sw/cmssw/pull/30016 https://github.com/cms-sw/cmssw/pull/30072 and https://github.com/cms-sw/cmssw/pull/30103

**Pull request merged**
