### PR TITLE
Final Phase-1 tagger versions

### PR DESCRIPTION
**Pull request by andrzejnovak**
Final model files for https://github.com/cms-sw/cmssw/pull/24918

### CODE REVIEW

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by slava77** [comment]
@mrodozov @smuzaffar 
do we have a way already to test a PR to an external repo without merging it first?

If not, changes here look "OK" (no strange files added or no existing ones unexpectedly removed): in this case this PR can be merged and we proceed to the testing step with a cmsdist PR.

**Comment by smuzaffar** [comment]
@slava77 , no not yet.

**Comment by mrodozov** [comment]
@slava77 almost there

**Pull request merged**
