### PR TITLE
Higgs Interaction Network Tagger Models in ONNX and PyTorch

### PR DESCRIPTION
**Pull request by jmduarte**
This PR provides the Higgs Interaction Network Tagger Models in ONNX and (originally) PyTorch. This version of the model was developed using open simulation (https://arxiv.org/abs/1909.12285) and presented in several BTV meetings (e.g. https://indico.cern.ch/event/833434/contributions/3495704/) and JMAR meetings (e.g. https://indico.cern.ch/event/856106/contributions/3613884/).

### CODE REVIEW

**Comment by mrodozov** [comment]
please test
the files are new, do you need them in to test with a cmssw piece or that comes later ?

**Comment by jmduarte** [comment]
Yes, they are needed for cms-sw/cmssw#30072

**Comment by mrodozov** [comment]
test parameters:
- pull_requests = cms-sw/cmssw#30072

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
+1

based on tests with cms-sw/cmssw#30072

**Comment by silviodonato** [comment]
merge

**Pull request merged**
