### PR TITLE
Merge ParticleNet AK4 and AK8 models for Run3

### PR DESCRIPTION
**Pull request by rgerosa**
We have developed new trainings for particle-net based on 12X simulated samples in Run3 conditions. This PR contains both models for AK4 jet flavour tagging and AK8 2-prong MD tagging. For each of the two cases, one onnx model for offline (RECO/miniAOD) and one for online (HLT) jets is provided. The HLT version of particle-net are meant to be used in the HH4b dedicated triggers proposed in the trigger review by the Higgs PAG [0]. 

[0] https://indico.cern.ch/event/1099590/contributions/4626739/attachments/2358674/4025770/TSGHIG_03Dec21.pdf

More details:
1. ParticleNetAK4/HLT/V00/ contains models for AK4PF jet tagging at HLT. Two distinct models are proposed: one able to classify b-jet/c-jet/uds-jet/gluon-jets, one adding hadronic tau-jets. In fact, we are studying possible improvements over DeepTau.
2. ParticleNetAK4/HLT/V00/ same networks as point 1. but trained on offline (reco) AK4CHS jets.
3. ParticleNetAK8/MD-2prong/HLT/  contains models for AK8PF 2-prong tagging at HLT (mass decorrelated). Two distinct models are proposed: one able to classify Xbb/Xcc/Xqq/Xgg/QCD, the second adds a Xtautau (hadronic tau) class.
4. ParticleNetAK8/MD-2prong/V02 same network as point 3. but trained on offline AK8Puppi jets.

These models are built starting from already existing particle-net models but training samples, input features, and NN hyper-parameters have been modified/tuned in order to achieve best performance & the possibility of being evaluated on both online and offline jets.

We will open soon another PR into cmssw-master in order merge changes needed for the evaluation. The HLT models will be used in Run3 data-taking. Instead, the RECO ones don't need, for the time being, to replace those used in standard sequences (RECO/MiniAOD). However, we would like to have them shipped as external to future CMSSW releases for testing/studying purposes given that it is always possible easily infere networks using miniAOD collections.

### CODE REVIEW

**Comment by rgerosa** [comment]
Following a private discussion with Marino and with BTV-HLT conveners, the PR has been updated as follows:

a) RECO models for these new versions of PNET have been excluded from this PR. They will be pushed in released with an independent PR later this month. Therefore, given that we are requesting to add only HLT models, I guess the review should be assigned to HLT.

b) Models have been moved from the ParticleNet directories inside the HLT one following the approach used in the recent PR that pushed DeepFlavour tagger for HLT. 
https://github.com/cms-data/RecoBTag-Combined/pull/46 

These PNET models cannot be tested immediately cause this PR depends on 
https://github.com/cms-sw/cmssw/pull/36862

However I'll provide soon a temporary recipe to test this PR by hand in order to validate the models.

**Comment by missirol** [comment]
assign hlt

based on https://github.com/cms-data/RecoBTag-Combined/pull/47#issuecomment-1031537568

**Comment by rgerosa** [comment]
@missirol here a manual recipe (running on GEN-SIM-RAW MC events) to test the PNET-HLT models that are subject of this PR but depends on the integration of another PR in CMSSW: 

cmsrel CMSSW_12_3_X_2022-02-07-1100
cd CMSSW_12_3_X_2022-02-07-1100/src
git-cms-init
git-cms-merge-topic rgerosa:particle-net-trigger-integration
scram b -j 8
git clone git@github.com:cms-data/RecoBTag-Combined.git
cd RecoBTag-Combined
git pull origin refs/pull/47/head
mkdir -p $CMSSW_BASE/external/data/RecoBTag/Combined/data/
scp -r HLT/* $CMSSW_BASE/external/data/RecoBTag/Combined/data/
cd ../
scp /afs/cern.ch/user/r/rgerosa/public/xMarino/hlt_mc_simplified_for_pnet.py ./
voms-proxy-init -voms cms
cmsRun hlt_mc_simplified_for_pnet.py inputFiles=/store/mc/Run3Summer21DRPremix/GluGluToHHTo4B_node_cHHH1_TuneCP5_14TeV-powheg-pythia8/GEN-SIM-DIGI-RAW/120X_mcRun3_2021_realistic_v6-v2/30000/edbef445-6b22-49ed-aea1-91c70733a0fd.root maxEvents=-1

Let me know if you also need a hlt-config to test the procedure on data. In this simplified menù there are just 4 paths using the four network models we are trying to push in this PR. Running on ggHH4b events ensures that a sufficient number of events survive the trigger selection to the point where the network is inferred.

**Comment by missirol** [comment]
please test

The PR tests won't tell much, as this PR does not affect them. I start them nonetheless to save some time (the tests would be triggered anyway later on by a signature).

**Comment by missirol** [comment]
+hlt

@rgerosa, thanks for the recipe. With that, I verified that HLT producers using the new data files in this PR run correctly (technically speaking ; i didnt do any physics validation).

@clacaputo @jpata , this PR requires your signature, but there are no RECO data files involved (similarly to other recent data PRs by HLT developers). TSG would like to have this PR merged in time for `pre5`. If possible, please have a look in the next few days. Thanks!

**Comment by missirol** [comment]
urgent

Just to signal that this PR targets `12_3_0_pre5`.

It only adds a few data files to be used in a future HLT menu, and it poses no risk for IBs.

**Comment by jpata** [comment]
+reconstruction
- nothing in reco as such (new models for HLT)

**Comment by perrotta** [comment]
+orp
- It adds a few datafiles needed for HLT development, with no interaction with the current workflows

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
