### PR TITLE
deepvertex weight files

### PR DESCRIPTION
**Pull request by leonardogiannini**
Weight file relative to the pull request https://github.com/cms-sw/cmssw/pull/26088

### CODE REVIEW

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by slava77** [comment]
@leonardogiannini 
Please clarify if this is still the latest training good for your needs.
Thank you.

**Comment by slava77** [comment]
> @leonardogiannini
> Please clarify if this is still the latest training good for your needs.
> Thank you.

ping

**Comment by smuzaffar** [comment]
do we still need this?

**Comment by slava77** [comment]
> do we still need this?

I think that we do, but I wanted to make sure that this remains the best available.

**Comment by leonardogiannini** [comment]
The weight files has to be updated as soon as the final training is ready. The PR is not meant for production anyway. 
(And sorry for the late reply)


@arizzi

**Comment by slava77** [comment]
On 5/20/19 2:26 PM, leonardogiannini wrote:
> The weight files has to be updated as soon as the final training is ready.

Please clarify when this will be available.
Is it days or months?

**Comment by leonardogiannini** [comment]
Unfortunately not in days. But it would be just a matter of changing the weights when ready.

**Comment by slava77** [comment]
+1

based on observations in https://github.com/cms-sw/cmssw/pull/26088#issuecomment-500061013
Even though this training is expected to be superseded soon (weeks?), it may already be useful in the release distribution at least for tests.

**Comment by fabiocos** [comment]
@slava77 @leonardogiannini I understand that this PR it is not needed for the integration of the CMSSW code, but it is needed to effectively use it

**Comment by slava77** [comment]
@fabiocos 
yes, it's useful for analysis/development use cases, it is not needed for production jobs.

**Comment by smuzaffar** [comment]
+externals
@fabiocos , should we integrate it.

**Comment by fabiocos** [comment]
@smuzaffar as it is just the addition of a new file, no reason not to do it, I overlooked it a bit as it was not strictly needed

**Comment by fabiocos** [comment]
+1

**Pull request merged**
