### PR TITLE
update ParticleNetAK4@HLT trainings for 2023 data-taking

### PR DESCRIPTION
**Pull request by scooperstein**
ParticleNet has been retrained in CMSSW 12_6_X with the latest HLT conditions and Run-3 MC samples. This network is meant to be included in a set of trigger paths for the 2023 data-taking V2 menu. Since taus are now included by default, there is no longer a separate network included without taus. Merging this pull request will enable the deployment of the new 2023 4j2b trigger paths.

Higgs trigger contacts: @mstamenk @portalesHEP
BTV@HLT conveners: @NiclasEich

@rgerosa

### CODE REVIEW

**Comment by missirol** [comment]
assign hlt

@scooperstein , please squash this PR in a single commit to clean the git history (so as to leave the V00 files untouched).

Some context: these new files are expected to be used in the near future in the 2023 HLT pp menu (they are specified as string parameters of a few modules of the HLT pp menu; see related comments in [CMSHLT-2695](https://its.cern.ch/jira/browse/CMSHLT-2695)). This means that
 - this PR does not depend on any open CMSSW PR
 - it simply adds a few files that would be integrated untested (this was also done in #47 , although there some manual validation was done)
 - the corresponding `cmsdist` update needs to be backported to `13_0_X`, and until there is a new `13_0_X` release with that, HLT would not be able to adopt the new cms-data files (the HLT menu expected to use these files should be integrated in CMSSW in the first week of May, so the new 13_0_X release should be in place by then) (for the integration in CMSSW, an IB with this cms-data update would be sufficient, but obviously for data-taking a new release is necessary).

**Comment by missirol** [comment]
@scooperstein , please see https://github.com/cms-data/RecoBTag-Combined/pull/52#issuecomment-1509203520 and update this PR. We can switch to the new PNet training at HLT only after this PR is is integrated in `13_0_X`.

**Comment by scooperstein** [comment]
Hi @missirol, all - sorry for the delay. We took a few days to update the ParticleNet@HLT AK8 model to remove a couple additional input variables that we did not use last year and were not necessary for the performance. With the training now included we use exactly the same input features as last year, such that we can use the same feature producer. I have also squashed the commits, as requested. Please let us know if there is anything further needed before merging.

**Comment by missirol** [comment]
+hlt

I tested the new cms-data files with a recent HLT menu [*], and saw no issue.

[*] Based on a customisation provided offline by @scooperstein.
```sh
#!/bin/bash

# cmsrel CMSSW_13_0_X_2023-04-18-2300
# cd CMSSW_13_0_X_2023-04-18-2300/src
# cmsenv
# git cms-addpkg RecoBTag/Combined
# git clone https://github.com/scooperstein/RecoBTag-Combined RecoBTag/Combined/data
# scram build

hltGetConfiguration /dev/CMSSW_13_0_0/GRun \
   --globaltag 126X_mcRun3_2023_forPU65_v3 \
   --mc \
   --unprescale \
   --output minimal \
   --max-events 200 \
   --input /store/mc/Run3Winter23Digi/GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-3p00_TuneCP5_13p6TeV_powheg-pythia8/GEN-SIM-RAW/GTv3Digi_126X_mcRun3_2023_forPU65_v3-v2/2560000/e1b2127c-442b-405e-9c19-c8429a2814e6.root \
   --eras Run3 --l1-emulator FullMC --l1 L1Menu_Collisions2023_v1_0_0_xml \
   > hlt.py

cmsRun hlt.py &> hlt1.log

cat <<@EOF >> hlt.py
process.hltParticleNetONNXJetTags.preprocess_json = 'RecoBTag/Combined/data/HLT/ParticleNetAK4/V01/preprocess.json'
process.hltParticleNetONNXJetTags.model_path = 'RecoBTag/Combined/data/HLT/ParticleNetAK4/V01/particle-net.onnx'
process.hltParticleNetONNXJetTags.flav_names = ['probtauhp', 'probtauhm', 'probb', 'probc', 'probuds', 'probg', 'ptcorr']
process.hltParticleNetDiscriminatorsJetTags.discriminators[0].denominator = ['hltParticleNetONNXJetTags:prob'+foo for foo in ['b', 'c', 'uds', 'g', 'tauhp', 'tauhm']]
process.hltParticleNetDiscriminatorsJetTags.discriminators[1].denominator = ['hltParticleNetONNXJetTags:prob'+foo for foo in ['b', 'c', 'uds', 'g', 'tauhp', 'tauhm']]
del process.hltParticleNetDiscriminatorsJetTags.discriminators[2]

process.hltParticleNetONNXJetTagsAK8.preprocess_json = 'RecoBTag/Combined/data/HLT/ParticleNetAK8/V01/preprocess.json'
process.hltParticleNetONNXJetTagsAK8.model_path = 'RecoBTag/Combined/data/HLT/ParticleNetAK8/V01/particle-net.onnx'
process.hltParticleNetONNXJetTagsAK8.flav_names = ['probHtt', 'probHtm', 'probHte', 'probHbb', 'probHcc', 'probHqq', 'probHgg', 'probQCD2hf', 'probQCD1hf', 'probQCD0hf']
process.hltParticleNetDiscriminatorsJetTagsAK8.discriminators[0].denominator = ['hltParticleNetONNXJetTagsAK8:prob'+foo for foo in ['Hbb', 'QCD2hf', 'QCD1hf', 'QCD0hf']]
process.hltParticleNetDiscriminatorsJetTagsAK8.discriminators[1].denominator = ['hltParticleNetONNXJetTagsAK8:prob'+foo for foo in ['Hcc', 'QCD2hf', 'QCD1hf', 'QCD0hf']]
process.hltParticleNetDiscriminatorsJetTagsAK8.discriminators[2].denominator = ['hltParticleNetONNXJetTagsAK8:prob'+foo for foo in ['Htt', 'QCD2hf', 'QCD1hf', 'QCD0hf']]
@EOF

cmsRun hlt.py &> hlt2.log
```

**Comment by missirol** [comment]
urgent

@perrotta @rappoccio , please consider merging this PR. It is needed for HLT development in `13_0_X`.

The RECO signature is pending, but the added files are unrelated to the offline reconstruction.

**Comment by perrotta** [comment]
please test
- There are only new files. and I really do not expect anythyng strange from the test, but let have them tested at least once before merging

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
