### PR TITLE
Phase2 DeepJet retraining model integration to CMSSW

### PR DESCRIPTION
**Pull request by hsinweihsia**
The BTV@HLT group has a Phase2 DeepJet retrained model. This PR is made to integrate the retrained DeepJet model into CMSSW. Please find the details in [7th HLT Upgrade Workshop](https://indico.cern.ch/event/1344917/#36-b-tagging-pog) and [here](https://indico.cern.ch/event/1393422/#3-round-robin-b-tagging-status).

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test with https://github.com/cms-sw/cmssw/pull/44431

**Comment by antoniovilela** [comment]
@hsinweihsia
Is this to be used only at HLT ?
Thanks.

**Comment by mmusich** [comment]
@antoniovilela 

>  Is this to be used only at HLT ?

does it make a difference? It's a new model and it's not yet used anywhere. 
The only customer at the moment is https://github.com/cms-sw/cmssw/pull/44431

**Comment by antoniovilela** [comment]
> @antoniovilela
> 
> > Is this to be used only at HLT ?
> 
> does it make a difference? It's a new model and it's not yet used anywhere. The only customer at the moment is [cms-sw/cmssw#44431](https://github.com/cms-sw/cmssw/pull/44431)

I would then ask @cms-sw/reconstruction-l2 to sign.
@mandrenguyen @jfernan2

**Comment by antoniovilela** [comment]
Please have a look at this cms-data PR.
@mandrenguyen @jfernan2

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
