### PR TITLE
add DeepDoubleB model V01 in GraphDef format

### PR DESCRIPTION
**Pull request by jmduarte**
This adds the DeepDoubleB model V01 transformed to a constant GraphDef format, as in the DeepFlavour case. Two version of the DeepDoubleB model V01 (one with a mass sculpting penalty and one without) are available. Both expect a minimum candidate pT of 0.95 (as in the DeepFlavour model).

These model files will be used for an imminent pull request for the DeepDoubleB model in CMSSW.
@cvernier @ferencek

### CODE REVIEW

**Comment by slava77** [comment]
DeepDoubleBV00/constant_graph.pb vs  DeepDoubleBV01_PtCut/constant_graph.pb 
can we keep the subdirectory naming more consistent?
Also, is it possible to put everything from  DeepDoubleB in a single directory?

**Comment by jmduarte** [comment]
Of course, what directory structure would be best? Something like:
```
DeepDoubleB/V00/constant_graph.pb (no pT cut, no mass sculpting penalty)
DeepDoubleB/V01/constant_graph.pb (candidate pT>0.95)
DeepDoubleB/V02/constant_graph.pb (candidate pT>0.95, mass sculpting penalty)
```
My only issue with this is it's not clear what the different versions are

**Comment by slava77** [comment]
On 4/19/18 1:05 PM, Javier Duarte wrote:
> Of course, what directory structure would be best? Something like:
> 
> |DeepDoubleB/V00/constant_graph.pb (no pT cut, no mass sculpting penalty)
> DeepDoubleB/V01/constant_graph.pb (candidate pT>0.95)
> DeepDoubleB/V02/constant_graph.pb (candidate pT>0.95, mass sculpting
> penalty) |
> 
> My only issue with this is it's not clear what the different versions are
> 

I don't have a preference for deeper subdirectories.

Since this is the first time this is introduced, and the PR title
mentions "V01", it was a bit strange to see "V00" submitted with it as well.
If all 3 (or more) will be needed and if the most likely version
evolution is a complete update of the set of training files,
then
DeepDoubleB/V01/
with constant_graph.pb , constant_graph_PtCut.pb  and
constant_graph_PtCut_MassSculptPen.pb
seems to be clear for longer term tracking of contents

**Comment by jmduarte** [comment]
Done. And since I can't imagine a use for "V00" moving forward, I've removed it.

**Comment by slava77** [comment]
@jmduarte 
will this be needed only for 10_2_X?

**Comment by jmduarte** [comment]
We would like to backport the CMSSW code to 9_4_X to make it more accessible for analysis of 2017 data, but I suppose this will have to be discussed further.

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
this PR adds new reasonably small files.
Please merge.
On the cmsdist side, we can start with just the 102X.
Thank you.

**Comment by smuzaffar** [comment]
done. cmsdist PR for 10.2.X is https://github.com/cms-sw/cmsdist/pull/3944

**Comment by slava77** [comment]
@smuzaffar 
thank you.

@jmduarte 
if you submit a PR with the code now, we should already be able to test it with automated tests.

**Pull request merged**
