### PR TITLE
[11.1.X] new PhaseII trainings for DeepCSV and DeepJet

### PR DESCRIPTION
**Pull request by mneukum**
Adding updated versions of DeepCSV and DeepJet training for PhaseII to CMSSW_11_1_X branch as discussed here:

https://github.com/cms-data/RecoBTag-Combined/pull/42#issuecomment-783425395

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
please test for CMSSW_11_1_X

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
please test for CMSSW_11_1_X

**Comment by slava77** [comment]
+1

the updated files are the same as in the master variant in #43 

comparisons in the jenkins tests show differences in the deepCSV variables as expected; but the tests do not have enough stats to confirm the behavior. So, the signoff is relying on the external validation: from p13 of https://indico.cern.ch/event/951596/contributions/4140990/attachments/2159414/3643026/2020_12_09_draft1.pdf which was shared in #42 
2020_12_09_draft1_p13
it looks like a moderate improvement is expected, at least in PU200.

**Comment by smuzaffar** [comment]
+externals
@silviodonato , @qliphy  this is for 11.1.X . I am merging it now in data external.

**Comment by fwyzard** [comment]
thanks

**Comment by silviodonato** [comment]
cc @upgrade

**Comment by silviodonato** [comment]
cc @cms-sw/upgrade-l2

**Pull request merged**
