### PR TITLE
Deep csv phase ii fix

### PR DESCRIPTION
**Pull request by dseith**
fixed the flight Distance variables in the training of the DeepCSV_PhaseII model. 

Despite the weights of the model, also the offsets and scales for the flightDistance variables have changed:

https://github.com/dseith/RecoBTag-Combined/blob/966f9531ab99acb7396378c199b4a4ccb3937b1e/DeepCSV_PhaseII.json#L315
https://github.com/dseith/RecoBTag-Combined/blob/966f9531ab99acb7396378c199b4a4ccb3937b1e/DeepCSV_PhaseII.json#L320
https://github.com/dseith/RecoBTag-Combined/blob/966f9531ab99acb7396378c199b4a4ccb3937b1e/DeepCSV_PhaseII.json#L325
https://github.com/dseith/RecoBTag-Combined/blob/966f9531ab99acb7396378c199b4a4ccb3937b1e/DeepCSV_PhaseII.json#L330

See also here: https://github.com/cms-sw/cmssw/pull/26072#issuecomment-490904185

### CODE REVIEW

**Comment by slava77** [comment]
@mrodozov @smuzaffar 
I think that this can be merged so that we can proceed to having a cmsdist PR available for tests of the cmssw PR.
(assuming that we are still in the old setup where cms-data PR can not be tested by itself and a cmsdist PR is needed)

**Comment by smuzaffar** [comment]
@slava77 , you can now test cms-data PRs too. If there is already a cmssw PR to test this then please start the tests by adding comment
`please test with cms-data/RecoBTag-Combined#23`
if this Pr should be tested alone then just comment here `please test`

**Comment by slava77** [comment]
> @slava77 , you can now test cms-data PRs too. If there is already a cmssw PR to test this then please start the tests by adding comment
> `please test with cms-data/RecoBTag-Combined#23`
> if this Pr should be tested alone then just comment here `please test`

Nice.
I started the tests.

**Comment by slava77** [comment]
+1

based on tests summarized in https://github.com/cms-sw/cmssw/pull/26072#issuecomment-491523264

**Comment by smuzaffar** [comment]
+externals
unit test failure is not related to this PR ( see https://github.com/cms-sw/cmssw/issues/26741 )

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
