### PR TITLE
Phase II models for DeepCSV and DeepJet

### PR DESCRIPTION
**Pull request by dseith**
Phase II models for DeepCSV and DeepJet as required in the PR here:

https://github.com/cms-sw/cmssw/pull/26072

### CODE REVIEW

**Comment by slava77** [comment]
@dseith 
what is the purpose of  DeepFlavourPhaseIIV01_94X_training.pb file?
I do not see it used in cms-sw/cmssw#26072

**Comment by dseith** [comment]
It is the Phase 2 model for DeepJet at some point we will have to provide it so I thought I could just add it with this commit. But I just realized the naming should rather be DeepJetPhaseIIV01_94X_training.pb
So it makes maybe more sense to make a separate PR for this.
I will  therefore remove it.

**Comment by slava77** [comment]
> It is the Phase 2 model for DeepJet at some point we will have to provide it so I thought I could just add it with this commit. But I just realized the naming should rather be DeepJetPhaseIIV01_94X_training.pb
> So it makes maybe more sense to make a separate PR for this.
> I will therefore remove it.

In case the file is not going to be used in the CMSSW production or training workflows, I think that it's better not to make this in the release because it will effectively have no customers.

**Comment by slava77** [comment]
compared to  DeepCSV_PhaseI.json, the new file  DeepCSV_PhaseII.json is about a factor of 100 larger (at least by the number of line counts: 372 vs 48K lines).
Is this difference well understood and necessary?

**Comment by dseith** [comment]
It is understood, but not necessary. 
In the old file all weights of the neural network for each layer are in one line, whereas in the new file there is one line per weight. This leads to a lot of additional lines. Indeed this is not really necessary. 
I will try to make the file more compact.

**Comment by dseith** [comment]
number of lines are now 374

**Comment by slava77** [comment]
@mrodozov @smuzaffar 
I think that this PR can now be merged.
please proceed with making a PR for cmsdist so that this external update can be tested with cms-sw/cmssw#26072.
Thank you.

**Comment by smuzaffar** [comment]
@slava77 , cmsdist PR is https://github.com/cms-sw/cmsdist/pull/4752

**Pull request merged**
