### PR TITLE
add model checksums

### PR DESCRIPTION
**Pull request by kpedro88**
for https://github.com/cms-sw/cmssw/issues/43695

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
[@cms-sw/reconstruction-l2](https://github.com/orgs/cms-sw/teams/reconstruction-l2) please sign so we can move to the next step of the plan in https://github.com/cms-sw/cmssw/issues/43695

**Comment by mandrenguyen** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Comment by rappoccio** [comment]
+1

**Pull request merged**
